import os
import requests

def send_interview_questions_email(recipient_email: str, candidate_name: str, questions: str):
    api_key = os.getenv("BREVO_API_KEY")
    
    if not api_key:
        raise ValueError("BREVO_API_KEY is not set in environment variables.")
    
    url = "https://api.brevo.com/v3/smtp/email"
    
    headers = {
        "accept": "application/json",
        "api-key": api_key,
        "content-type": "application/json"
    }
    
    html_content = f"""
    <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
        <h2 style="color: #2E7D32;">AI Interview Questions Report</h2>
        <p><b>Candidate Name:</b> {candidate_name}</p>
        <p>Here are the targeted technical interview questions generated by Gemini AI based on the resume and job description gap analysis:</p>
        
        <div style="background-color: #f9f9f9; padding: 15px; border-left: 4px solid #2E7D32; border-radius: 4px; margin-top: 15px;">
            <pre style="font-family: Arial, sans-serif; white-space: pre-wrap; font-size: 14px;">{questions}</pre>
        </div>
        
        <p style="margin-top: 20px; font-size: 12px; color: #777;">
            Best regards,<br>
            <b>AI Resume Screener SaaS Platform</b>
        </p>
    </div>
    """
    
    payload = {
        "sender": {"name": "AI Resume Screener", "email": "a.subair888@gmail.com"},
        "to": [{"email": recipient_email}],
        "subject": f"Technical Interview Questions - {candidate_name}",
        "htmlContent": html_content
    }
    response = requests.post(url, json=payload, headers=headers)
    
    if response.status_code in [200, 201, 202]:
        return True
    else:
        raise Exception(f"Failed to send email via Brevo API: {response.text}")